#pragma once

#include "../GpNetworkHttpCore_global.hpp"
#include "../../../../GpCore2/GpUtils/Types/Enums/GpEnum.hpp"
#include "../../../../GpCore2/GpUtils/Types/Strings/GpStringOps.hpp"

namespace GPlatform {

GP_ENUM(GP_NETWORK_HTTP_CORE_API, GpHttpResponseCode,
    CONTINUE_100,
    SWITCHING_PROTOCOLS_101,
    PROCESSING_102,
    EARLY_HINTS_103,
    OK_200,
    CREATED_201,
    ACCEPTED_202,
    NON_AUTHORITATIVE_INFORMATION_203,
    NO_CONTENT_204,
    RESET_CONTENT_205,
    PARTIAL_CONTENT_206,
    MULTIPLE_CHOICES_300,
    MOVED_PERMANENTLY_301,
    FOUND_302,
    SEE_OTHER_303,
    NOT_MODIFIED_304,
    USE_PROXY_305,
    SWITCH_PROXY_306,
    TEMPORARY_REDIRECT_307,
    PERMANENT_REDIRECT_308,
    BAD_REQUEST_400,
    UNAUTHORIZED_401,
    PAYMENT_REQUIRED_402,
    FORBIDDEN_403,
    NOT_FOUND_404,
    METHOD_NOT_ALLOWED_405,
    NOT_ACCEPTABLE_406,
    PROXY_AUTHENTICATION_REQUIRED_407,
    REQUEST_TIMEOUT_408,
    CONFLICT_409,
    GONE_410,
    LENGTH_REQUIRED_411,
    PRECONDITION_FAILED_412,
    PAYLOAD_TOO_LARGE_413,
    URI_TOO_LONG_414,
    UNSUPPORTED_MEDIA_TYPE_415,
    RANGE_NOT_SATISFIABLE_416,
    EXPECTATION_FAILED_417,
    INTERNAL_SERVER_ERROR_500,
    NOT_IMPLEMENTED_501,
    BAD_GATEWAY_502,
    SERVICE_UNAVAILABLE_503,
    GATEWAY_TIMEOUT_504,
    HTTP_VERSION_NOT_SUPPORTED_505,
    VARIANT_ALSO_NEGOTIATES_506
);

class GP_NETWORK_HTTP_CORE_API GpHttpResponseCodeUtils
{
public:
    static GpHttpResponseCode::EnumT    SFromId (const size_t aCodeId);
};

}//namespace GPlatform
